name: CI

on:
  push:
    branches: [feat/attn-ta]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
